---
class: 4
flags: 0x0000
unid: OF39085B33A9E3B805-ON004EA32F85257AC2
items:
  - name: $DesignerVersion
    type: text
    data: "9"
    signed: true
  - name: $FileNames
    type: text
    data: ".settings/.jsdtscope"
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $LANGUAGE
    type: text
    data: en
    signed: true
  - name: $Revisions
    type: time
    data: "2012-11-26T09:18:55.85-05:00"
  - name: $TITLE
    type: text
    data: ".settings/.jsdtscope"
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []