---
ACL:
  opaque: |
    Q0ECAKoBBwAAAAAABgAoABAAiACoAAEAAAAoAAQAAAAEBCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AHJjaGl2ZU1hbmFnZXIAAMYAAACCAQAAAAAAAAAAAAAAAPAAAABaAToBAAAAAAAAAABFQQIAAAAAAAAA
    AAAAAAUACQAtRGVmYXVsdC0AAABFQQAAAAAAAAAAAAAAAEcAFABbT3RoZXJEb21haW5TZXJ2ZXJzXQBk
    GgFFQQYAAAAAAAAAAAAAANoBFABbTG9jYWxEb21haW5TZXJ2ZXJzXQAzAABFQQMAAAAAAAAAAAAAABgA
    CwBbLURlZmF1bHQtXQAAAEVBAAAAAAAAAAAAAAAABQALAFtBbm9ueW1vdXNdAAAARUEGAAAAAAAAAAAA
    AACYARIATG9jYWxEb21haW5TZXJ2ZXJzAEIAAEVBAAAAAAAAAAAAAAAARgASAE90aGVyRG9tYWluU2Vy
    dmVycwAA
DBOptions: 0x00000000
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0